# Generated by Django 3.2.20 on 2023-07-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=25)),
                ('amount', models.IntegerField()),
                ('uat', models.DateTimeField()),
            ],
        ),
    ]
